// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEDN4HML6JHtTWLI_yxBVGyV46J4RXDY',
    appId: '1:422706958150:web:4a2f6e143b3787388e5f47',
    messagingSenderId: '422706958150',
    projectId: 'cloud-vault-df35b',
    authDomain: 'cloud-vault-df35b.firebaseapp.com',
    storageBucket: 'cloud-vault-df35b.firebasestorage.app',
    measurementId: 'G-21MTR0J78B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVUOxpu_0MmzzdMjZ51z3j0J2cnO7y5c',
    appId: '1:422706958150:android:128c0a02b29f3dca8e5f47',
    messagingSenderId: '422706958150',
    projectId: 'cloud-vault-df35b',
    storageBucket: 'cloud-vault-df35b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4ZZKyb0XiZljCk_NldJB2_kIdU5whxA',
    appId: '1:422706958150:ios:8b204e7f8bceeaf68e5f47',
    messagingSenderId: '422706958150',
    projectId: 'cloud-vault-df35b',
    storageBucket: 'cloud-vault-df35b.firebasestorage.app',
    iosBundleId: 'com.example.cloudVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4ZZKyb0XiZljCk_NldJB2_kIdU5whxA',
    appId: '1:422706958150:ios:8b204e7f8bceeaf68e5f47',
    messagingSenderId: '422706958150',
    projectId: 'cloud-vault-df35b',
    storageBucket: 'cloud-vault-df35b.firebasestorage.app',
    iosBundleId: 'com.example.cloudVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEDN4HML6JHtTWLI_yxBVGyV46J4RXDY',
    appId: '1:422706958150:web:61130e79592c5ad78e5f47',
    messagingSenderId: '422706958150',
    projectId: 'cloud-vault-df35b',
    authDomain: 'cloud-vault-df35b.firebaseapp.com',
    storageBucket: 'cloud-vault-df35b.firebasestorage.app',
    measurementId: 'G-T2E3KL9NY0',
  );
}
